conversion to syled-components
Davit-Avakian/Nba-App pull request #1
Opened 2022-09-29 14:16 UTC by Davit-Avakian

2022-10-03 08:29 UTC, NareOP requested changes
Overall feedback:
the code and file structures look good to me, I can see detailed designing approaches to the components. Excellent work on that! 

Please also consider:

- the naming of the PR and commits and branch names, don't overload one commit with lots of changes do it separately, so it'll be easy to organize, it'll be understandable for other developers and modifications can be seen independently.
- add eslint and prettier to the project, so you can keep your code formatted, and avoid minor mistakes.
- keep one type of metric in your code, use just rem in your styling (for small sizes like 3px, you can keep the px, it's much understandable)
- we usually keep images and fonts in src/assets folder, please keep that
- for the class namings of CSS classes we use kebab-case
- instead of relative paths use path aliases, fyi read [this](https://dev.to/rfornal/create-path-aliases-in-react-2oid) article

2022-10-09 11:39 UTC, yaser-op requested changes
too many files, what are these for?
<img width="950" alt="image" src="https://user-images.githubusercontent.com/77053897/194754723-9df5990c-a550-4e95-b04b-988b0dfdeb80.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/77053897/194754789-b0f3253b-2419-462f-b685-0bf3430fb7c9.png">

2022-10-10 16:29 UTC, yaser-op requested changes
include video recording or screenshots for all pages desktop & mobile

2022-10-10 16:29 UTC, yaser-op commented on src/App.js
> +            <SecondWrapper>
rename to more appropriate name; something like `SecondaryWrapper`

2022-10-10 16:29 UTC, yaser-op commented on src/components/AroundNba/index.js
> +                <img src={images[image]} />
in a real app this is not the way to do it, the item that you are showing will contain the image url, update the `aroundNba` object to add the image url there and in the view render the image received .

applies everywhere else

2022-10-10 16:29 UTC, yaser-op commented on src/components/Coverage/styles.js
> +  flex-direction: row !important;
avoid using `!important`

2022-10-10 16:29 UTC, yaser-op commented on src/components/Coverage/styles.js
> +  background-color: #ffff;
this is used in several styles, move the colors to a global file and use it everywhere

2022-10-11 13:30 UTC, NareOP requested changes
Good work, but be attentive on how you show the data, first of all look at the web page and separate similar elements in your mind, make components and their styling dynamic as much as possible.

2022-10-11 13:30 UTC, NareOP commented on src/components/Footer/index.js
>          </div>
I can see the same structure a few times, so make this dynamic as well

2022-10-11 13:30 UTC, NareOP commented on src/components/AroundNba/index.js
> +              <a href="">
what's the purpose of a tag here?

2022-10-11 13:30 UTC, NareOP commented on src/components/AroundNba/index.js
> +              </NewsItem>
please take out this element, I saw something like this in another file too, make it shared element

2022-10-11 13:30 UTC, NareOP commented on src/components/Header/index.js
> +            </Link>
same structure, do it with map and do the same for Menu component

2022-10-11 13:30 UTC, NareOP commented on src/components/SocialMedias/index.js
>          </a>
use map

2022-10-11 13:30 UTC, NareOP commented on src/components/Standings/index.js
> +              color: `${conference === 'East' ? 'white' : 'black'}`
remove inline styles for code readability, do it in styled-components with props

2022-10-19 16:52 UTC, merged